name: dbt CI

on:
  pull_request:
    branches: [test-ci-setup]
    paths:
      - "Dbtcloud_analytics/**"
      - "Dbtcloud_analytics/.github/workflows/config.yaml"
jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - run: pip install dbt-databricks

      - run: dbt deps

      - run: dbt parse

      - run: dbt build --select state:modified+
