name: dbt--Merge--CI

on:
  push:
    branches: [test-ci-setup]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - run: pip install dbt-databricks

      - run: dbt deps

      - run: dbt parse

      - run: dbt build --select state:modified+